---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-laravel
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/root/laravel-app/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-laravel
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi

